name: Deploy Laravel Backend

on:
  push:
    branches: [ "12.x" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Upload deploy script
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.BACKEND_HOST }}
          username: ${{ secrets.BACKEND_USER }}
          key: ${{ secrets.BACKEND_SSH_KEY }}
          source: "deploy.sh"
          target: "/home/${{ secrets.BACKEND_USER }}/"

      - name: Deploy via SSH to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.BACKEND_HOST }} #IPaddr of the instance 
          username: ${{ secrets.BACKEND_USER }} #User like Ubuntu
          key: ${{ secrets.BACKEND_SSH_KEY }}
          script: |
            chmod +x ~/deploy.sh
            sudo ~/deploy.sh
      
